
services:
# application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_PASSWORD=example
      - DB_NAME=node_app_db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
# database
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
     - data-base:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: node_app_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # redis cache
  redis:
      image: redis:alpine
      restart: always
      ports:
        - '6379:6379'
      volumes: 
        - redis:/data

  

volumes:
  data-base:
  redis:
    driver: local
